/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import {
  Employee,
  LeaveRequest,
  Conflict,
  MonthlyAbsenceStat,
  NovedadType,
  RequestState,
  DocumentRecord,
  PaySlip,
  VersionHistoryRecord,
} from "./types";

export const initialEmployees: Employee[] = [
  {
    id: "EMP-2941",
    firstName: "Rodrigo Hernán",
    lastName: "Silva",
    department: "IT & Desarrollo",
    role: "Senior Fullstack Developer",
    status: "ACTIVO",
    hireDate: "02 de Enero, 2019",
    email: "r.silva@precisionhr.com",
    phone: "+54 11 4455-2233",
    cuil: "20-33842910-8",
    birthDate: "14 de Mayo, 1988 (36 años)",
    maritalStatus: "Casado",
    address: "Av. del Libertador 4500, Piso 12B, CABA",
    emergencyContact: {
      name: "Laura Montenegro",
      relationship: "Esposa",
      phone: "+54 11 5566-7788",
    },
    workedDaysThisMonth: 18,
    totalDaysThisMonth: 22,
    totalFiles: 14,
    vigenteFiles: 11,
    vencidosFiles: 2,
    rechazadosFiles: 1,
  },
  {
    id: "EMP-24592",
    firstName: "Luis Angel",
    lastName: "Batallan",
    department: "Operaciones",
    role: "Administrador de Infraestructura",
    status: "ACTIVO",
    hireDate: "15 de Marzo, 2015",
    email: "l.batallan@precisionhr.com",
    phone: "+54 11 9988-7766",
    cuil: "20-24592331-9",
    birthDate: "28 de Agosto, 1982 (43 años)",
    maritalStatus: "Casado",
    address: "Av. Santa Fe 1200, Palermo, CABA",
    emergencyContact: {
      name: "María Batallan",
      relationship: "Hermana",
      phone: "+54 11 8877-6655",
    },
    workedDaysThisMonth: 20,
    totalDaysThisMonth: 22,
    totalFiles: 12,
    vigenteFiles: 10,
    vencidosFiles: 1,
    rechazadosFiles: 1,
  },
  {
    id: "EMP-2948",
    firstName: "Martina",
    lastName: "Rodriguez",
    department: "Marketing",
    role: "Social Media Strategist",
    status: "ACTIVO",
    hireDate: "15 de Julio, 2021",
    email: "m.rodriguez@precisionhr.com",
    phone: "+54 11 3456-7890",
    cuil: "27-29488392-4",
    birthDate: "03 de Noviembre, 1994 (31 años)",
    maritalStatus: "Soltero",
    address: "Sarmiento 845, Almagro, CABA",
    emergencyContact: {
      name: "Esteban Rodriguez",
      relationship: "Padre",
      phone: "+54 11 2345-6789",
    },
    workedDaysThisMonth: 15,
    totalDaysThisMonth: 22,
    totalFiles: 8,
    vigenteFiles: 7,
    vencidosFiles: 1,
    rechazadosFiles: 0,
  },
  {
    id: "EMP-4410",
    firstName: "Javier",
    lastName: "Casal",
    department: "IT Ops",
    role: "Database Administrator",
    status: "ACTIVO",
    hireDate: "10 de Abril, 2020",
    email: "j.casal@precisionhr.com",
    phone: "+54 11 4321-8765",
    cuil: "20-44101928-3",
    birthDate: "19 de Junio, 1990 (35 años)",
    maritalStatus: "Soltero",
    address: "Corrientes 3400, CABA",
    emergencyContact: {
      name: "Sofía Casal",
      relationship: "Madre",
      phone: "+54 11 1234-5678",
    },
    workedDaysThisMonth: 19,
    totalDaysThisMonth: 22,
    totalFiles: 10,
    vigenteFiles: 9,
    vencidosFiles: 0,
    rechazadosFiles: 1,
  },
  {
    id: "EMP-1122",
    firstName: "Sofia",
    lastName: "Mendez",
    department: "Ventas",
    role: "Ejecutivo de Cuentas Senior",
    status: "ACTIVO",
    hireDate: "11 de Septiembre, 2018",
    email: "s.mendez@precisionhr.com",
    phone: "+54 11 8765-4321",
    cuil: "27-11223948-2",
    birthDate: "21 de Diciembre, 1985 (40 años)",
    maritalStatus: "Divorciado",
    address: "Cabildo 2000, Belgrano, CABA",
    emergencyContact: {
      name: "Marcos Mendez",
      relationship: "Hijo",
      phone: "+54 11 8765-4321",
    },
    workedDaysThisMonth: 14,
    totalDaysThisMonth: 22,
    totalFiles: 15,
    vigenteFiles: 13,
    vencidosFiles: 2,
    rechazadosFiles: 0,
  },
  {
    id: "EMP-3009",
    firstName: "Andres",
    lastName: "Ferrari",
    department: "Finanzas",
    role: "Analista Financiero",
    status: "ACTIVO",
    hireDate: "05 de Mayo, 2022",
    email: "a.ferrari@precisionhr.com",
    phone: "+54 11 2345-6782",
    cuil: "20-30091823-1",
    birthDate: "12 de Febrero, 1996 (30 años)",
    maritalStatus: "Soltero",
    address: "Av. Pueyrredón 1500, Recoleta, CABA",
    emergencyContact: {
      name: "Lucía Ferrari",
      relationship: "Hermana",
      phone: "+54 11 3456-7892",
    },
    workedDaysThisMonth: 17,
    totalDaysThisMonth: 22,
    totalFiles: 6,
    vigenteFiles: 6,
    vencidosFiles: 0,
    rechazadosFiles: 0,
  },
  {
    id: "EMP-4482",
    firstName: "Marcos",
    lastName: "Alvarez",
    department: "Comercial",
    role: "Asesor Comercial",
    status: "ACTIVO",
    hireDate: "15 de Mayo, 2021",
    email: "m.alvarez@precisionhr.com",
    phone: "+54 11 9831-2941",
    cuil: "20-44829102-1",
    birthDate: "12 de Abril, 1992 (34 años)",
    maritalStatus: "Casado",
    address: "Thames 2200, Palermo, CABA",
    emergencyContact: {
      name: "Carla Alvarez",
      relationship: "Esposa",
      phone: "+54 11 9831-2942",
    },
    workedDaysThisMonth: 18,
    totalDaysThisMonth: 22,
    totalFiles: 5,
    vigenteFiles: 4,
    vencidosFiles: 1,
    rechazadosFiles: 0,
  },
  {
    id: "EMP-5102",
    firstName: "Sofía",
    lastName: "Rodríguez",
    department: "Administración",
    role: "Asistente Administrativa",
    status: "ACTIVO",
    hireDate: "02 de Enero, 2020",
    email: "s.rodriguez@precisionhr.com",
    phone: "+54 11 1122-3344",
    cuil: "27-51023941-8",
    birthDate: "15 de Octubre, 1993 (35 años)",
    maritalStatus: "Soltero",
    address: "Av. Rivadavia 4500, Caballito, CABA",
    emergencyContact: {
      name: "Olga Rodríguez",
      relationship: "Madre",
      phone: "+54 11 1122-3345",
    },
    workedDaysThisMonth: 21,
    totalDaysThisMonth: 22,
    totalFiles: 8,
    vigenteFiles: 8,
    vencidosFiles: 0,
    rechazadosFiles: 0,
  },
  {
    id: "EMP-4412",
    firstName: "Carlos",
    lastName: "Gómez",
    department: "Ventas",
    role: "Ejecutivo de Ventas",
    status: "INACTIVO",
    hireDate: "14 de Febrero, 2018",
    exitDate: "14 de Marzo, 2023",
    email: "c.gomez@precisionhr.com",
    phone: "+54 11 9911-2233",
    cuil: "20-44123941-1",
    birthDate: "05 de Septiembre, 1988 (37 años)",
    maritalStatus: "Divorciado",
    address: "Soler 3900, Palermo, CABA",
    emergencyContact: {
      name: "Marta Gómez",
      relationship: "Madre",
      phone: "+54 11 9911-2234",
    },
    workedDaysThisMonth: 0,
    totalDaysThisMonth: 0,
    totalFiles: 12,
    vigenteFiles: 0,
    vencidosFiles: 0,
    rechazadosFiles: 0,
  },
  {
    id: "EMP-7721",
    firstName: "Sofía",
    lastName: "Blanco",
    department: "Operaciones",
    role: "Analista de Operaciones",
    status: "ACTIVO",
    hireDate: "11 de Agosto, 2022",
    email: "s.blanco@precisionhr.com",
    phone: "+54 11 8831-2914",
    cuil: "27-77213941-2",
    birthDate: "23 de Enero, 1995 (31 años)",
    maritalStatus: "Soltero",
    address: "Honduras 4100, Palermo, CABA",
    emergencyContact: {
      name: "Alberto Blanco",
      relationship: "Padre",
      phone: "+54 11 8831-2915",
    },
    workedDaysThisMonth: 19,
    totalDaysThisMonth: 22,
    totalFiles: 7,
    vigenteFiles: 7,
    vencidosFiles: 0,
    rechazadosFiles: 0,
  },
  {
    id: "EMP-1156",
    firstName: "Roberto",
    lastName: "Torres",
    department: "Tecnología",
    role: "Analista QA Senior",
    status: "ACTIVO",
    hireDate: "30 de Junio, 2019",
    email: "r.torres@precisionhr.com",
    phone: "+54 11 3914-1923",
    cuil: "20-11563914-1",
    birthDate: "09 de Julio, 1989 (36 años)",
    maritalStatus: "Casado",
    address: "Suipacha 900, San Nicolás, CABA",
    emergencyContact: {
      name: "Diana Torres",
      relationship: "Esposa",
      phone: "+54 11 3914-1924",
    },
    workedDaysThisMonth: 18,
    totalDaysThisMonth: 22,
    totalFiles: 11,
    vigenteFiles: 10,
    vencidosFiles: 1,
    rechazadosFiles: 0,
  },
  {
    id: "EMP-2290",
    firstName: "Elena",
    lastName: "Pardo",
    department: "Administración",
    role: "Administradora General",
    status: "ACTIVO",
    hireDate: "22 de Noviembre, 2021",
    email: "e.pardo@precisionhr.com",
    phone: "+54 11 3914-2914",
    cuil: "27-22903914-2",
    birthDate: "14 de Marzo, 1987 (39 años)",
    maritalStatus: "Casado",
    address: "Paraguay 1500, Recoleta, CABA",
    emergencyContact: {
      name: "Juan Pardo",
      relationship: "Esposo",
      phone: "+54 11 3914-2915",
    },
    workedDaysThisMonth: 20,
    totalDaysThisMonth: 22,
    totalFiles: 9,
    vigenteFiles: 8,
    vencidosFiles: 1,
    rechazadosFiles: 0,
  },
];

export const initialRequests: LeaveRequest[] = [
  {
    id: "REQ-01",
    employeeId: "EMP-2948",
    employeeName: "Martina Rodriguez",
    department: "Marketing",
    type: NovedadType.ESTUDIO,
    startDate: "2025-10-15",
    endDate: "2025-10-18",
    days: 4,
    state: RequestState.PENDIENTE,
    observations: "Examen final de Planificación Estratégica Digital (UADE).",
    submissionDate: "2025-10-01",
  },
  {
    id: "REQ-02",
    employeeId: "EMP-4410",
    employeeName: "Javier Casal",
    department: "IT Ops",
    type: NovedadType.PARTICULAR,
    startDate: "2025-10-20",
    endDate: "2025-10-20",
    days: 1,
    state: RequestState.PENDIENTE,
    observations: "Trámite de renovación de pasaporte en oficina central de RENAPER.",
    submissionDate: "2025-10-05",
  },
  {
    id: "REQ-03",
    employeeId: "EMP-1122",
    employeeName: "Sofia Mendez",
    department: "Ventas",
    type: NovedadType.ENFERMEDAD,
    startDate: "2025-10-18",
    endDate: "2025-10-25",
    days: 8,
    state: RequestState.PENDIENTE,
    observations: "Reposo médico certificado por faringitis aguda.",
    attachedFile: "certificado_mendez.pdf",
    submissionDate: "2025-10-17",
  },
  {
    id: "REQ-04",
    employeeId: "EMP-3009",
    employeeName: "Andres Ferrari",
    department: "Finanzas",
    type: NovedadType.ESTUDIO,
    startDate: "2025-11-10",
    endDate: "2025-11-12",
    days: 3,
    state: RequestState.PENDIENTE,
    observations: "Examen final de Contabilidad Gerencial (UBA).",
    submissionDate: "2025-10-25",
  },
  {
    id: "REQ-05", // Shown in Screenshot 5
    employeeId: "EMP-2041",
    employeeName: "Javier Peralta",
    department: "Logística",
    type: NovedadType.MEDICA,
    startDate: "2025-11-10",
    endDate: "2025-11-15",
    days: 6,
    state: RequestState.PENDIENTE,
    observations: "Licencia médica anual obligatoria o rehabilitación traumatológica.",
    submissionDate: "2025-11-01",
  },
  {
    id: "REQ-06",
    employeeId: "EMP-2941",
    employeeName: "Rodrigo Hernán Silva",
    department: "IT & Desarrollo",
    type: NovedadType.ESTUDIO,
    startDate: "2025-04-12",
    endDate: "2025-04-12",
    days: 1,
    state: RequestState.PROCESADO,
    observations: "Examen final 'Ingeniería de Software II' (Universidad de Palermo).",
    submissionDate: "2025-04-05",
  },
];

export const initialConflicts: Conflict[] = [
  {
    id: "CONF-01",
    team: "Marketing",
    severity: "CRITICAL",
    description: "30% del equipo de Marketing estará ausente durante este periodo.",
    statusText: "30% del equipo ausente",
    relatedRequests: [
      {
        employeeName: "M. Rodriguez",
        state: "Pendiente",
        range: "15 Oct - 18 Oct",
        type: NovedadType.ESTUDIO,
      },
      {
        employeeName: "P. Lopez",
        state: "Aprobado",
        range: "16 Oct - 17 Oct",
        type: NovedadType.PARTICULAR,
      },
    ],
  },
  {
    id: "CONF-02",
    team: "IT Ops / Infraestructura",
    severity: "WARNING",
    description: "Personal Crítico Ausente. Solo 1 Administrador quedará activo en IT Ops.",
    statusText: "Key Personnel",
    relatedRequests: [
      {
        employeeName: "J. Casal",
        state: "Pendiente",
        range: "20 Oct",
        type: NovedadType.PARTICULAR,
      },
    ],
  },
  {
    id: "CONF-03",
    team: "Logística",
    severity: "CRITICAL",
    description: "Superposición detectada: Javier Peralta y 2 empleados más del equipo de Logística tienen solicitudes para la misma semana (10 Nov - 17 Nov).",
    statusText: "Superposición crítica",
    relatedRequests: [
      {
        employeeName: "Javier Peralta",
        state: "Pendiente",
        range: "10 Nov - 15 Nov",
        type: NovedadType.MEDICA,
      },
      {
        employeeName: "Daniel Rossi",
        state: "Aprobado",
        range: "11 Nov - 14 Nov",
        type: NovedadType.COMPENSATORIO,
      },
    ],
  },
];

export const monthlyAbsenceStats: MonthlyAbsenceStat[] = [
  { month: "Ene", particular: 40, enfermedad: 20, compensatorio: 10, estudio: 12 },
  { month: "Feb", particular: 30, enfermedad: 45, compensatorio: 8, estudio: 5 },
  { month: "Mar", particular: 60, enfermedad: 15, compensatorio: 30, estudio: 25 },
  { month: "Abr", particular: 20, enfermedad: 10, compensatorio: 12, estudio: 15 },
  { month: "May", particular: 50, enfermedad: 30, compensatorio: 18, estudio: 10 },
  { month: "Jun", particular: 40, enfermedad: 40, compensatorio: 15, estudio: 22 },
  { month: "Jul", particular: 10, enfermedad: 5, compensatorio: 20, estudio: 4 },
  { month: "Ago", particular: 45, enfermedad: 25, compensatorio: 24, estudio: 12 },
];

export const employeeDocuments: Record<string, DocumentRecord[]> = {
  "EMP-2941": [
    {
      id: "DOC-01",
      name: "DNI Frente y Dorso",
      fileName: "DNI_Silva_Frente_v2.pdf",
      category: "Identidad",
      status: "VIGENTE",
      expiryDate: "2028-05-15",
      updatedDate: "12 Ene 2024",
    },
    {
      id: "DOC-02",
      name: "Título Grado Ingeniería",
      fileName: "Licenciatura_Sistemas.pdf",
      category: "Académico",
      status: "VIGENTE",
      expiryDate: undefined,
      updatedDate: "15 Oct 2023",
    },
    {
      id: "DOC-03",
      name: "Contrato Laboral 2024",
      fileName: "Silva_Contract_2024.pdf",
      category: "Contractual",
      status: "VIGENTE",
      expiryDate: "2024-12-31",
      updatedDate: "01 Jun 2024",
    },
    {
      id: "DOC-04",
      name: "Certificado de Salud Anual",
      fileName: "Certificado_Anual_Apto.pdf",
      category: "Médico",
      status: "POR VENCER",
      expiryDate: "2026-06-25", // Since local current time is Jun 2026, expiring soon or expired soon.
      updatedDate: "10 Mar 2025",
    },
    {
      id: "DOC-05",
      name: "Seguro Vida Obligatorio",
      fileName: "Seguro_Vida_Firmar.pdf",
      category: "Legales",
      status: "RECHAZADO",
      expiryDate: undefined,
      updatedDate: "15 de Noviembre, 2025",
      rejectReason: "Falta firma hológrafa o digital del empleado en sección anexa.",
    },
  ],
};

export const paySlipsData: Record<string, PaySlip[]> = {
  "EMP-2941": [
    { id: "PS-01", period: "Julio 2025", generatedDate: "05/08/2025", signed: true },
    { id: "PS-02", period: "Junio 2025", generatedDate: "03/07/2025", signed: true },
    { id: "PS-03", period: "Mayo 2025", generatedDate: "05/06/2025", signed: true },
  ],
};

export const versionHistoryData: Record<string, VersionHistoryRecord[]> = {
  "EMP-2941": [
    {
      id: "VH-01",
      title: "Nueva versión: Contrato Laboral 2024",
      detail: "Subido por RRHH (Laura M.) • v2.0",
      date: "12/02/2024",
    },
    {
      id: "VH-02",
      title: "Documento Archivado: Contrato Laboral 2023",
      detail: "Archivado automáticamente por sistema",
      date: "01/01/2024",
      archived: true,
    },
    {
      id: "VH-03",
      title: "Actualización de DNI (Frente)",
      detail: "Subido por Rodrigo Silva",
      date: "15/11/2023",
    },
  ],
};
